Update test.yaml
Signed-off-by: Vivek Patil <139427417+vivekpatil-uptycs@users.noreply.github.com>

diff --git a/test.yaml b/test.yaml
--- a/test.yaml
+++ b/test.yaml
@@ -1,25 +1,20 @@
-apiVersion: batch/v1
-kind: Job
+apiVersion: v1
+kind: PodTemplate
 metadata:
-  name: security-scan-job
+  labels:
+    app: security-scan-podtemplate
 spec:
-  template:
-    metadata:
-      labels:
-        app: security-scan-job
-    spec:
-      containers:
-      - name: security-scan-container
-        image: busybox:latest
-        command:
-          - "/bin/sh"
-          - "-c"
-          - >
-            if capsh --print | grep -E 'ALL|all|NET_RAW'; then
-              echo "Error: Container has prohibited capabilities" >&2
-              exit 1
-            else
-              echo "Container passed security scan"
-            fi
-      restartPolicy: Never
-  backoffLimit: 3
+  containers:
+  - name: security-scan-container
+    image: busybox:latest
+    command:
+      - "/bin/sh"
+      - "-c"
+      - >
+        if capsh --print | grep -E 'ALL|all|NET_RAW'; then
+          echo "Error: Container has prohibited capabilities" >&2
+          exit 1
+        else
+          echo "Container passed security scan"
+        fi
+  restartPolicy: Always
